---
title: "7and14"
author: "Elias Lai"
subtitle: ElMallah Lab, Duke University
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, comment = NA, 
                      message = FALSE, warning = FALSE,
                      fig.height = 6, fig.width = 9, fig.align = "center")
```

```{r load-packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(conflicted)
library(Seurat)
library(CellChat)
library(patchwork)
library(reticulate)
library(ComplexHeatmap)
library(enrichR)
library(DropletUtils)
library(dplyr)
library(Matrix)
library(cowplot)
library(sctransform)
library(ggplot2)
library(SoupX)
library(here)
library(pheatmap)
library(biomaRt)
library(EnhancedVolcano)
library(slingshot)
library(RColorBrewer)
library(scales)
options(future.globals.maxSize= 8912896000000)
col_p = c("#F3E5C2","#EFB89A","#EF8F50", "#F5731D","#FA4602","#FE5100")
options(stringsAsFactors = FALSE)
conflict_prefer("union", "BiocGenerics")
conflict_prefer("slice", "dplyr")
conflict_prefer("filter", "dplyr")
```

```{r read_in_files, message=FALSE, warning=FALSE}
merge <- readRDS("output/merge.rds")
merge.markers <- readRDS("output/merge.markers.rds")

cmp_seven <- readRDS("output/cmp_seven.rds")
cmp_seven.markers <- readRDS("output/cmp_seven.markers.rds")

cmp_fourteen <- readRDS("output/cmp_fourteen.rds")
cmp_fourteen.markers <- readRDS("output/cmp_fourteen.markers.rds")
```

```{r split, message=FALSE, warning=FALSE}
merge_split <- SplitObject(merge, split.by = "condition")
gaako <- merge_split$`GAA KO`
control <- merge_split$Control

wt_alveolarfibroblast <- subset(control, idents = 'AlveolarFibroblast')
ko_seven <- subset(gaako, idents = '7')

wt_endothelial <- subset(control, idents = c("Endothelial", "Endothelial2"))
ko_fourteen <- subset(gaako, idents = '14')

#recombine
cmp_seven <- merge(x=wt_alveolarfibroblast,y=ko_seven)
cmp_fourteen <- merge(x=wt_endothelial,y=ko_fourteen)
```

```{r redo_prep, message=FALSE, warning=FALSE}
#seven
cmp_seven <- NormalizeData(cmp_seven, normalization.method = "LogNormalize", scale.factor = 10000)
cmp_seven <- FindVariableFeatures(cmp_seven, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(cmp_seven)
cmp_seven <- ScaleData(cmp_seven, features = all.genes)
cmp_seven <- RunPCA(object = cmp_seven, verbose = FALSE)
ElbowPlot(cmp_seven, ndims = 30)
cmp_seven <- FindNeighbors(object = cmp_seven, dims = 1:20)
cmp_seven <- FindClusters(object = cmp_seven, resolution = 1)
cmp_seven <- RunUMAP(object = cmp_seven, dims = 1:20,min.dist = 1, n.neighbors = 40, spread = 5, local.connectivity = 20)

DimPlot(cmp_seven, reduction = "umap", label = TRUE)
DimPlot(cmp_seven, reduction = "umap", label = F,group.by = "condition")
saveRDS(cmp_seven, file = "output/cmp_seven.rds")

#fourteen
cmp_fourteen <- NormalizeData(cmp_fourteen, normalization.method = "LogNormalize", scale.factor = 10000)
cmp_fourteen <- FindVariableFeatures(cmp_fourteen, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(cmp_fourteen)
cmp_fourteen <- ScaleData(cmp_fourteen, features = all.genes)
cmp_fourteen <- RunPCA(object = cmp_fourteen, verbose = FALSE)
ElbowPlot(cmp_fourteen, ndims = 30)
cmp_fourteen <- FindNeighbors(object = cmp_fourteen, dims = 1:20)
cmp_fourteen <- FindClusters(object = cmp_fourteen, resolution = 1)
cmp_fourteen <- RunUMAP(object = cmp_fourteen, dims = 1:20,min.dist = 1, n.neighbors = 40, spread = 5, local.connectivity = 20)

DimPlot(cmp_fourteen, reduction = "umap", label = TRUE)
DimPlot(cmp_fourteen, reduction = "umap", label = F,group.by = "condition")
saveRDS(cmp_fourteen, file = "output/cmp_fourteen.rds")
```

```{r reidentify, message=FALSE, warning=FALSE}
#seven
DimPlot(cmp_seven, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
cmp_seven <- RenameIdents(cmp_seven,
                    '5' = "Seven",
                    '6' = "Seven",
                    '0' = "AlveolarFibroblast",
                    '1' = "AlveolarFibroblast",
                    '2' = "AlveolarFibroblast",
                    '3' = "AlveolarFibroblast",
                    '4' = "AlveolarFibroblast",
                    '7' = "AlveolarFibroblast",
                    '8' = "AlveolarFibroblast")

#fourteen
DimPlot(cmp_fourteen, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
cmp_fourteen <- RenameIdents(cmp_fourteen,
                    '7' = "Fourteen",
                    '8' = "Fourteen",
                    '9' = "Fourteen",
                    '0' = "Endothelial",
                    '1' = "Endothelial",
                    '2' = "Endothelial",
                    '3' = "Endothelial",
                    '4' = "Endothelial",
                    '5' = "Endothelial",
                    '6' = "Endothelial",
                    '10' = "Endothelial",
                    '11' = "Endothelial")
```


```{r refindmarkers, message=FALSE, warning=FALSE}
#seven
cmp_seven.markers <- FindMarkers(cmp_seven,
                                    ident.2 = "AlveolarFibroblast", ident.1 = "Seven")
saveRDS(cmp_seven.markers, file = "output/cmp_seven.markers.rds")

#fourteen
cmp_fourteen.markers <- FindMarkers(cmp_fourteen,
                                    ident.2 = "Endothelial", ident.1 = "Fourteen",
                                    min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(cmp_fourteen.markers, file = "output/cmp_fourteen.markers.rds")

cmp_fourteen.markers <- FindMarkers(merge, ident.1 = "14",
                                    min.pct = 0.2, only.pos = T)
```

```{r EnhancedVolcano, message=FALSE, warning=FALSE}
EnhancedVolcano(cmp_seven.markers,
                title = "WT Alveolar Fibroblast vs GAAKO Cluster 7",
                #  selectLab = m$V1,
                lab = rownames(cmp_seven.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = T,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(cmp_fourteen.markers,
                title = "WT Endothelial vs GAAKO Cluster 14",
                #  selectLab = m$V1,
                lab = rownames(cmp_fourteen.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = T,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()
```











