---
title: "Merge"
author: "Elias Lai"
subtitle: ElMallah Lab, Duke University
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, comment = NA, 
                      message = FALSE, warning = FALSE,
                      fig.height = 6, fig.width = 9, fig.align = "center")
```

```{r load-packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(conflicted)
library(Seurat)
library(CellChat)
library(patchwork)
library(enrichR)
library(DropletUtils)
library(dplyr)
library(Matrix)
library(cowplot)
library(sctransform)
library(ggplot2)
library(SoupX)
library(here)
library(pheatmap)
library(biomaRt)
library(EnhancedVolcano)
library(slingshot)
library(RColorBrewer)
library(scales)
options(future.globals.maxSize= 8912896000000)
col_p = c("#F3E5C2","#EFB89A","#EF8F50", "#F5731D","#FA4602","#FE5100")

# gaa <- readRDS("output/gaa.rds")
# gaa.markers <- readRDS("output/gaamarkers.rds")
# gaa_withoutdoublets <- readRDS("output/gaa_withoutdoublets.rds")
# control <- readRDS("output/control.rds")
# control.markers <- readRDS("output/controlmarkers.rds")
# control_withoutdoublets <- readRDS("output/control_withoutdoublets.rds")
# gaa_merge <- readRDS("output/gaa_merge.rds")
# gaa_merge.markers <- readRDS("output/gaa_merge.markers.rds")
# gaa_merge_withoutdoublets1 <- readRDS("output/gaa_merge_withoutdoublets1.rds")

# merge1 <- readRDS("output/merge1.rds")
# merge1.markers <- readRDS("output/merge1.markers.rds")
merge <- readRDS("output/merge.rds")
merge.markers <- readRDS("output/merge.markers.rds")


# matrix1 <- readRDS("output/matrix1.rds")
# endothelial <- readRDS("output/endothelial.rds")
# endothelial.markers <- readRDS("output/endothelial.markers.rds")
# smoothmuscle <- readRDS("output/smoothmuscle.rds")
# smoothmuscle.markers <- readRDS("output/smoothmuscle.markers.rds")
# pericyte <- readRDS("output/pericyte.rds")
# pericyte.markers <- readRDS("output/pericyte.markers.rds")
# type2pneumocyte <- readRDS("output/type2pneumocyte.rds")
# type2pneumocyte.markers <- readRDS("output/type2pneumocyte.markers.rds")
# type1pneumocyte <- readRDS("output/type1pneumocyte.rds")
# type1pneumocyte.markers <- readRDS("output/type1pneumocyte.markers.rds")
# ciliated <- readRDS("output/ciliated.rds")
# ciliated.markers <- readRDS("output/ciliated.markers.rds")
# mesothelial <- readRDS("output/mesothelial.rds")
# mesothelial.markers <- readRDS("output/mesothelial.markers.rds")
# alveolarfibroblast <- readRDS("output/alveolarfibroblast.rds")
# alveolarfibroblast.markers <- readRDS("output/alveolarfibroblast.markers.rds")
# adventitialfibroblast <- readRDS("output/adventitialfibroblast.rds")
# adventitialfibroblast.markers <- readRDS("output/adventitialfibroblast.markers.rds")
# gcb <- readRDS("output/gcb.rds")
# gcb.markers <- readRDS("output/gcb.markers.rds")
# immune <- readRDS("output/immune.rds")
# immune.markers <- readRDS("output/immune.markers.rds")
# capillaryendothelial <- readRDS("output/capillaryendothelial.rds")
# capillaryendothelial.markers <- readRDS("output/capillaryendothelial.markers.rds")
# lymphaticendothelial <- readRDS("output/lymphaticendothelial.rds")
# lymphaticendothelial.markers <- readRDS("output/lymphaticendothelial.markers.rds")
# peribronchial <- readRDS("output/peribronchial.rds")
# peribronchial.markers <- readRDS("output/peribronchial.markers.rds")
```

```{r setup, message = FALSE, warning = FALSE}
control_withoutdoublets$condition <- "Control"
gaa_withoutdoublets$condition <- "GAA KO"

gaa_merge <- merge(x=control_withoutdoublets,y=c(gaa_withoutdoublets))
saveRDS(gaa_merge, file = "output/gaa_merge.rds")
rm(gaa_withoutdoublets, control_withoutdoublets)

gaa_merge <- NormalizeData(gaa_merge, normalization.method = "LogNormalize", scale.factor = 10000)
gaa_merge <- FindVariableFeatures(gaa_merge, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(gaa_merge)
gaa_merge <- ScaleData(gaa_merge, features = all.genes)
gaa_merge <- RunPCA(object = gaa_merge, verbose = FALSE)
ElbowPlot(gaa_merge, ndims = 30)
gaa_merge <- FindNeighbors(object = gaa_merge, dims = 1:20)
gaa_merge <- FindClusters(object = gaa_merge, resolution = 1)
gaa_merge <- RunUMAP(object = gaa_merge, dims = 1:20,min.dist = 1, n.neighbors = 40, spread = 5, local.connectivity = 20)

DimPlot(gaa_merge, reduction = "umap", label = TRUE)
DimPlot(gaa_merge, reduction = "umap", label = F,group.by = "condition")
saveRDS(gaa_merge, file = "output/gaa_merge.rds")

gaa_merge.markers <- FindAllMarkers(gaa_merge, only.pos = TRUE, min.pct = 0.25,
                                  logfc.threshold = 0.25)
saveRDS(gaa_merge.markers, file = "output/gaa_merge.markers.rds")
```

```{r featureplots, message = FALSE, warning = FALSE}
DimPlot(gaa_merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
# Cluster 3: Alveolar Fibroblast
FeaturePlot(gaa_merge, c("Ces1d", "Wnt2", "Pdgfra"))
# Cluster #: Adventitial Fibroblast
FeaturePlot(gaa_merge, c("Pi16", "Pdgfra"))
# Cluster #: Pericyte
FeaturePlot(gaa_merge, c("Hhip", "Pdgfra"))
# Cluster 5: Mesothelial
FeaturePlot(gaa_merge, c("Dcn", "Msln", "Wt1"))
# Cluster 7: Capillary Endothelial
FeaturePlot(gaa_merge, c("Tmem100", "Ednrb", "Pecam1"))
# Cluster 8: Smooth Muscle
FeaturePlot(gaa_merge, c("Acta2", "Myh11"))
# Cluster 9: Type 2 Pneumocytes
FeaturePlot(gaa_merge, c("Sftpc", "Sftpd"))
# Cluster 15: Lymphatic Endothelial
FeaturePlot(gaa_merge, c("Mmrn1", "Lyve1", "Pecam1"))
# Cluster 17: Ciliated
FeaturePlot(gaa_merge, c("Foxj1"))
# Cluster 18: Goblet+Club+Basal
FeaturePlot(gaa_merge, c("Scgb1a1", "Bpifb1"))
# Cluster 19: Type 1 Pneumocytes
FeaturePlot(gaa_merge, c("Rtkn2"))
# Cluster 20: B
FeaturePlot(gaa_merge, c("Cd79b", "Ptprc"))
# Cluster 21: CD8+ T
FeaturePlot(gaa_merge, c("Trbc2", "Cd8b1", "Ly6c2", "Ptprc"))
```

```{r label, message = FALSE, warning = FALSE}
DimPlot(gaa_merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
gaa_merge <- RenameIdents(gaa_merge, 
                    '4' = "Endothelial",
                    '29' = "Endothelial",
                    '1' = "Endothelial",
                    '15' = "Endothelial",
                    '11' = "Endothelial",
                    '18' = "Endothelial",
                    '7' = "Endothelial",
                    '26' = "Endothelial",
                    '14' = "Endothelial",
                    '13' = "Smooth Muscle",
                    '12' = "Pericyte",
                    '9' = "Type II Pneumocyte",
                    '24' = "Type II Pneumocyte",
                    '20' = "Type I Pneumocyte",
                    '16' = "Ciliated",
                    '30' = "Mesothelial",
                    '6' = "Mesothelial",
                    '17' = "Mesothelial",
                    '21' = "Fibroblast",
                    '25' = "Fibroblast",
                    '3' = "Fibroblast",
                    '28' = "Fibroblast",
                    '10' = "Fibroblast",
                    '2' = "Fibroblast",
                    '5' = "Fibroblast",
                    '0' = "Fibroblast",
                    '8' = "Fibroblast",
                    '19' = "Goblet+Club+Basal",
                    '23' = "Immune")
DimPlot(gaa_merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
```

```{r subset, message=FALSE, warning=FALSE}
# resolution 10
gaa_merge <- FindClusters(gaa_merge, resolution = 10)
DimPlot(gaa_merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
gaa_merge_rm_clusters <- c(107, 110, 68, 120, 118, 116)
gaa_merge_withoutdoublets1 <- subset(x = gaa_merge, 
                                     idents = gaa_merge_rm_clusters, invert = TRUE)
# resolution 20
gaa_merge_withoutdoublets1 <- FindClusters(gaa_merge_withoutdoublets1, resolution = 90)
DimPlot(gaa_merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
gaa_merge_rm_clusters <- c(107, 110, 68, 120, 118, 116)
gaa_merge_withoutdoublets1 <- subset(x = gaa_merge, 
                                     idents = gaa_merge_rm_clusters, invert = TRUE)
# Overall UMAP
DimPlot(gaa_merge_withoutdoublets1, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
```

```{r remove_doublets, message=FALSE, warning=FALSE}
# resolution 90, 396
gaa_merge <- FindClusters(gaa_merge, resolution = 90)
DimPlot(gaa_merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
gaa_merge_rm_clusters <- c(352, 585, 24, 184, 356, 132, 179, 301, 456, 598, 486, 320, 433, 396, 479, 267, 488, 559, 347, 108, 39, 336, 553, 141, 407, 171, 306, 124, 431, 259)
gaa_merge_withoutdoublets <- subset(x = gaa_merge, 
                                     idents = gaa_merge_rm_clusters, invert = TRUE)
DimPlot(gaa_merge_withoutdoublets, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
saveRDS(gaa_merge_withoutdoublets, file = "output/gaa_merge_withoutdoublets.rds")
```


```{r redo, message=FALSE, warning=FALSE}
rm(gaa_merge, gaa_merge.markers, gaa_merge_rm_clusters)
merge <- gaa_merge_withoutdoublets
merge <- NormalizeData(merge, normalization.method = "LogNormalize", scale.factor = 10000)
merge <- FindVariableFeatures(merge, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(merge)
merge <- ScaleData(merge, features = all.genes)
merge <- RunPCA(object = merge, verbose = FALSE)
ElbowPlot(merge, ndims = 30)
merge <- FindNeighbors(object = merge, dims = 1:20)
merge <- FindClusters(object = merge, resolution = 1)
merge <- RunUMAP(object = merge, dims = 1:20,min.dist = 1, n.neighbors = 40, spread = 5, local.connectivity = 20)

DimPlot(merge, reduction = "umap", label = TRUE)
DimPlot(merge, reduction = "umap", label = F,group.by = "condition")
saveRDS(merge, file = "output/merge.rds")

merge.markers <- FindAllMarkers(merge, only.pos = TRUE, min.pct = 0.25,
                                  logfc.threshold = 0.25)
saveRDS(merge.markers, file = "output/merge.markers.rds")
DimPlot(merge, reduction = "umap", label = TRUE, pt.size = 0.001)
```

```{r featureplots-merge, message = FALSE, warning = FALSE}
DimPlot(merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
# Cluster 3: Alveolar Fibroblast
FeaturePlot(merge, c("Ces1d", "Npnt", "Wnt2", "Pdgfra"))
# Cluster #: Adventitial Fibroblast
FeaturePlot(merge, c("Pi16", "Ccl11", "Il33", "Adh7", "Pdgfra"))
# Cluster #: Pericyte
FeaturePlot(merge, c("Pdgfrb", "Cspg4", "Mcam"))
# Cluster #: Peribronchial Fibroblast
FeaturePlot(merge, c("Hhip", "Pdgfra", "Fgf18"))
# Cluster 5: Mesothelial
FeaturePlot(merge, c("Dcn", "Msln", "Wt1"))
# Cluster 7: Capillary Endothelial
FeaturePlot(merge, c("Tmem100", "Ednrb", "Pecam1"))
# Cluster 8: Smooth Muscle
FeaturePlot(merge, c("Acta2", "Myh11"))
# Cluster 9: Type 2 Pneumocytes
FeaturePlot(merge, c("Sftpc", "Sftpd"))
# Cluster 15: Lymphatic Endothelial
FeaturePlot(merge, c("Mmrn1", "Lyve1", "Pecam1"))
# Cluster 17: Ciliated
FeaturePlot(merge, c("Foxj1"))
# Cluster 18: Goblet+Club+Basal
FeaturePlot(merge, c("Scgb1a1", "Bpifb1"))
# Cluster 19: Type 1 Pneumocytes
FeaturePlot(merge, c("Rtkn2"))
# Cluster 20: B
FeaturePlot(merge, c("Cd79b", "Ptprc"))
# Cluster 21: CD8+ T
FeaturePlot(merge, c("Trbc2", "Cd8b1", "Ly6c2", "Ptprc"))
```

```{r relabeling, message=FALSE, warning=FALSE}
merge <- FindClusters(object = merge, resolution = 1)
merge <- RenameIdents(merge,
                    '0' = "Endothelial2",
                    '3' = "Endothelial",
                    '12' = "Endothelial",
                    '15' = "LymphaticEndothelial",
                    '8' = "CapillaryEndothelial",
                    '19' = "CapillaryEndothelial",
                    '26' = "CapillaryEndothelial",
                    '16' = "SmoothMuscle",
                    '22' = "Pericyte",
                    '10' = "Type2Pneumocyte",
                    '24' = "Type1Pneumocyte",
                    '17' = "Ciliated",
                    '5' = "Mesothelial",
                    '21' = "Mesothelial",
                    '11' = "AdventitialFibroblast",
                    '9' = "AdventitialFibroblast",
                    '4' = "AdventitialFibroblast",
                    '20' = "AlveolarFibroblast",
                    '6' = "AlveolarFibroblast",
                    '2' = "AlveolarFibroblast",
                    '1' = "AlveolarFibroblast",
                    '18' = "Goblet+Club+Basal",
                    '13' = "Peribronchial",
                    '23' = "Immune")
DimPlot(merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
merge <- StashIdent(merge, save.name = "clusters")
saveRDS(merge, file = "output/merge.rds")
```

```{r finalsubsets, message=FALSE, warning=FALSE}
endothelial <- subset(x = merge, idents = "Endothelial")
saveRDS(endothelial, file = "output/endothelial.rds")
smoothmuscle <- subset(x = merge, idents = "SmoothMuscle")
saveRDS(smoothmuscle, file = "output/smoothmuscle.rds")
pericyte <- subset(x = merge, idents = "Pericyte")
saveRDS(pericyte, file = "output/pericyte.rds")
type2pneumocyte <- subset(x = merge, idents = "Type2Pneumocyte")
saveRDS(type2pneumocyte, file = "output/type2pneumocyte.rds")
type1pneumocyte <- subset(x = merge, idents = "Type1Pneumocyte")
saveRDS(type1pneumocyte, file = "output/type1pneumocyte.rds")
ciliated <- subset(x = merge, idents = "Ciliated")
saveRDS(ciliated, file = "output/ciliated.rds")
mesothelial <- subset(x = merge, idents = "Mesothelial")
saveRDS(mesothelial, file = "output/mesothelial.rds")
alveolarfibroblast <- subset(x = merge, idents = "AlveolarFibroblast")
adventitialfibroblast <- subset(x = merge, idents = "AdventitialFibroblast")
gcb <- subset(x = merge, idents = "Goblet+Club+Basal")
saveRDS(gcb, file = "output/gcb.rds")

immune <- subset(x = merge, idents = "Immune")
saveRDS(immune, file = "output/immune.rds")

capillaryendothelial <- subset(x = merge, idents = "CapillaryEndothelial")
saveRDS(capillaryendothelial, file = "output/capillaryendothelial.rds")
lymphaticendothelial <- subset(x = merge, idents = "LymphaticEndothelial")
saveRDS(lymphaticendothelial, file = "output/lymphaticendothelial.rds")
peribronchial <- subset(x = merge, idents = "Peribronchial")
saveRDS(peribronchial, file = "output/peribronchial.rds")
seven <- subset(x = merge, idents = "7")
saveRDS(seven, file = "output/seven.rds")
fourteen <- subset(x = merge, idents = c(14))
saveRDS(fourteen, file = "output/fourteen.rds")
twentyfive <- subset(x = merge, idents = c(25))
saveRDS(twentyfive, file = "output/twentyfive.rds")
```

```{r clean+subset_gcb, message=FALSE, warning=FALSE}
gcb <- readRDS("output/gcb.rds")
gcb.markers <- readRDS("output/gcb.markers.rds")
gcb <- NormalizeData(gcb, normalization.method = "LogNormalize", scale.factor = 10000)
gcb <- FindVariableFeatures(gcb, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(gcb)
gcb <- ScaleData(gcb, features = all.genes)
gcb <- RunPCA(object = gcb, verbose = FALSE)
ElbowPlot(gcb, ndims = 30)
gcb <- FindNeighbors(object = gcb, dims = 1:20)
gcb <- FindClusters(object = gcb, resolution = 1)
gcb <- RunUMAP(object = gcb, dims = 1:20,min.dist = 1, n.neighbors = 40, spread = 5, local.connectivity = 20)
DimPlot(gcb, reduction = "umap", label = TRUE)
DimPlot(gcb, reduction = "umap", label = F,group.by = "condition")
saveRDS(gcb, file = "output/gcb.rds")
gcb.markers <- FindAllMarkers(gcb, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
saveRDS(gcb.markers, file = "output/gcb.markers.rds")
DimPlot(gcb, reduction = "umap", label = TRUE, pt.size = 0.001)

FeaturePlot(gcb, c("Scgb1a1", "Bpifb1", "Sox2", "Krt5"))
gcb <- FindClusters(object = gcb, resolution = 8)
DimPlot(gcb, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
DimPlot(gcb, reduction = "umap", label = F,group.by = "condition")

# Cleaned

gcb_rm_clusters <- c(5, 3)
gcb_cleaned <- subset(x = gcb, idents = gcb_rm_clusters, invert = TRUE)
DimPlot(gcb_cleaned, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
saveRDS(gcb_cleaned, file = "output/gcb_cleaned.rds")

gcb_cleaned <- NormalizeData(gcb_cleaned, normalization.method = "LogNormalize", scale.factor = 10000)
gcb_cleaned <- FindVariableFeatures(gcb_cleaned, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(gcb_cleaned)
gcb_cleaned <- ScaleData(gcb_cleaned, features = all.genes)
gcb_cleaned <- RunPCA(object = gcb_cleaned, verbose = FALSE)
ElbowPlot(gcb_cleaned, ndims = 30)
gcb_cleaned <- FindNeighbors(object = gcb_cleaned, dims = 1:20)
gcb_cleaned <- FindClusters(object = gcb_cleaned, resolution = 1)
gcb_cleaned <- RunUMAP(object = gcb_cleaned, dims = 1:20,min.dist = 1, n.neighbors = 40, spread = 5, local.connectivity = 20)
DimPlot(gcb_cleaned, reduction = "umap", label = TRUE)
DimPlot(gcb_cleaned, reduction = "umap", label = F,group.by = "condition")
saveRDS(gcb_cleaned, file = "output/gcb_cleaned.rds")
gcb_cleaned.markers <- FindAllMarkers(gcb_cleaned, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
saveRDS(gcb_cleaned.markers, file = "output/gcb_cleaned.markers.rds")
DimPlot(gcb_cleaned, reduction = "umap", label = TRUE, pt.size = 0.001)

FeaturePlot(gcb_cleaned, c("Scgb1a1", "Bpifb1", "Sox2", "Krt5"))
gcb_cleaned <- FindClusters(object = gcb_cleaned, resolution = 8)
DimPlot(gcb_cleaned, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
DimPlot(gcb_cleaned, reduction = "umap", label = F,group.by = "condition")

# Subset gcb
gcb_cleaned <- FindClusters(object = gcb_cleaned, resolution = 1)
DimPlot(gcb_cleaned, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
basal <- subset(x = gcb_cleaned, idents = c(2))
goblet <- subset(x = gcb_cleaned, idents = c(1))
club <- subset(x = gcb_cleaned, idents = c(0, 4))

#goblet+club+basal prep
Idents(goblet) <- goblet$condition
goblet.markers <- FindMarkers(goblet,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(goblet.markers, file = "output/goblet.markers.rds")
saveRDS(goblet, file = "output/goblet")

Idents(basal) <- basal$condition
basal.markers <- FindMarkers(basal,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(basal.markers, file = "output/basal.markers.rds")
saveRDS(basal, file = "output/basal")

Idents(club) <- club$condition
club.markers <- FindMarkers(club,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(club.markers, file = "output/club.markers.rds")
saveRDS(club, file = "output/club")
```

```{r normalize, message=FALSE, warning=FALSE}
#endothelial
endothelial <- NormalizeData(endothelial, normalization.method = "LogNormalize", scale.factor = 10000)
endothelial <- FindVariableFeatures(endothelial, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(endothelial)
endothelial <- ScaleData(endothelial, features = all.genes)
endothelial <- RunPCA(object = endothelial, verbose = FALSE)
ElbowPlot(endothelial, ndims = 30)
endothelial <- FindNeighbors(object = endothelial, dims = 1:20)

#smoothmuscle
smoothmuscle <- NormalizeData(smoothmuscle, normalization.method = "LogNormalize", scale.factor = 10000)
smoothmuscle <- FindVariableFeatures(smoothmuscle, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(smoothmuscle)
smoothmuscle <- ScaleData(smoothmuscle, features = all.genes)
smoothmuscle <- RunPCA(object = smoothmuscle, verbose = FALSE)
ElbowPlot(smoothmuscle, ndims = 30)
smoothmuscle <- FindNeighbors(object = smoothmuscle, dims = 1:20)

#pericyte
pericyte <- NormalizeData(pericyte, normalization.method = "LogNormalize", scale.factor = 10000)
pericyte <- FindVariableFeatures(pericyte, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pericyte)
pericyte <- ScaleData(pericyte, features = all.genes)
pericyte <- RunPCA(object = pericyte, verbose = FALSE)
ElbowPlot(pericyte, ndims = 30)
pericyte <- FindNeighbors(object = pericyte, dims = 1:20)

#type2pneumocyte
type2pneumocyte <- NormalizeData(type2pneumocyte, normalization.method = "LogNormalize", scale.factor = 10000)
type2pneumocyte <- FindVariableFeatures(type2pneumocyte, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(type2pneumocyte)
type2pneumocyte <- ScaleData(type2pneumocyte, features = all.genes)
type2pneumocyte <- RunPCA(object = type2pneumocyte, verbose = FALSE)
ElbowPlot(type2pneumocyte, ndims = 30)
type2pneumocyte <- FindNeighbors(object = type2pneumocyte, dims = 1:20)

#type1pneumocyte
type1pneumocyte <- NormalizeData(type1pneumocyte, normalization.method = "LogNormalize", scale.factor = 10000)
type1pneumocyte <- FindVariableFeatures(type1pneumocyte, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(type1pneumocyte)
type1pneumocyte <- ScaleData(type1pneumocyte, features = all.genes)
type1pneumocyte <- RunPCA(object = type1pneumocyte, verbose = FALSE)
ElbowPlot(type1pneumocyte, ndims = 30)
type1pneumocyte <- FindNeighbors(object = type1pneumocyte, dims = 1:20)

#ciliated
ciliated <- NormalizeData(ciliated, normalization.method = "LogNormalize", scale.factor = 10000)
ciliated <- FindVariableFeatures(ciliated, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(ciliated)
ciliated <- ScaleData(ciliated, features = all.genes)
ciliated <- RunPCA(object = ciliated, verbose = FALSE)
ElbowPlot(ciliated, ndims = 30)
ciliated <- FindNeighbors(object = ciliated, dims = 1:20)

#mesothelial
mesothelial <- NormalizeData(mesothelial, normalization.method = "LogNormalize", scale.factor = 10000)
mesothelial <- FindVariableFeatures(mesothelial, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(mesothelial)
mesothelial <- ScaleData(mesothelial, features = all.genes)
mesothelial <- RunPCA(object = mesothelial, verbose = FALSE)
ElbowPlot(mesothelial, ndims = 30)
mesothelial <- FindNeighbors(object = mesothelial, dims = 1:20)

#alveolarfibroblast
alveolarfibroblast <- NormalizeData(alveolarfibroblast, normalization.method = "LogNormalize", scale.factor = 10000)
alveolarfibroblast <- FindVariableFeatures(alveolarfibroblast, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(alveolarfibroblast)
alveolarfibroblast <- ScaleData(alveolarfibroblast, features = all.genes)
alveolarfibroblast <- RunPCA(object = alveolarfibroblast, verbose = FALSE)
ElbowPlot(alveolarfibroblast, ndims = 30)
alveolarfibroblast <- FindNeighbors(object = alveolarfibroblast, dims = 1:20)

#adventitialfibroblast
adventitialfibroblast <- NormalizeData(adventitialfibroblast, normalization.method = "LogNormalize", scale.factor = 10000)
adventitialfibroblast <- FindVariableFeatures(adventitialfibroblast, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(adventitialfibroblast)
adventitialfibroblast <- ScaleData(adventitialfibroblast, features = all.genes)
adventitialfibroblast <- RunPCA(object = adventitialfibroblast, verbose = FALSE)
ElbowPlot(adventitialfibroblast, ndims = 30)
adventitialfibroblast <- FindNeighbors(object = adventitialfibroblast, dims = 1:20)

#goblet
goblet <- NormalizeData(goblet, normalization.method = "LogNormalize", scale.factor = 10000)
goblet <- FindVariableFeatures(goblet, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(goblet)
goblet <- ScaleData(goblet, features = all.genes)
goblet <- RunPCA(object = goblet, verbose = FALSE)
ElbowPlot(goblet, ndims = 30)
goblet <- FindNeighbors(object = goblet, dims = 1:20)

#club
club <- NormalizeData(club, normalization.method = "LogNormalize", scale.factor = 10000)
club <- FindVariableFeatures(club, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(club)
club <- ScaleData(club, features = all.genes)
club <- RunPCA(object = club, verbose = FALSE)
ElbowPlot(club, ndims = 30)
club <- FindNeighbors(object = club, dims = 1:20)

#basal
basal <- NormalizeData(basal, normalization.method = "LogNormalize", scale.factor = 10000)
basal <- FindVariableFeatures(basal, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(basal)
basal <- ScaleData(basal, features = all.genes)
basal <- RunPCA(object = basal, verbose = FALSE)
ElbowPlot(basal, ndims = 30)
basal <- FindNeighbors(object = basal, dims = 1:20)

#immune
immune <- NormalizeData(immune, normalization.method = "LogNormalize", scale.factor = 10000)
immune <- FindVariableFeatures(immune, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(immune)
immune <- ScaleData(immune, features = all.genes)
immune <- RunPCA(object = immune, verbose = FALSE)
ElbowPlot(immune, ndims = 30)
immune <- FindNeighbors(object = immune, dims = 1:20)

#capillaryendothelial
capillaryendothelial <- NormalizeData(capillaryendothelial, normalization.method = "LogNormalize", scale.factor = 10000)
capillaryendothelial <- FindVariableFeatures(capillaryendothelial, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(capillaryendothelial)
capillaryendothelial <- ScaleData(capillaryendothelial, features = all.genes)
capillaryendothelial <- RunPCA(object = capillaryendothelial, verbose = FALSE)
ElbowPlot(capillaryendothelial, ndims = 30)
capillaryendothelial <- FindNeighbors(object = capillaryendothelial, dims = 1:20)

#lymphaticendothelial
lymphaticendothelial <- NormalizeData(lymphaticendothelial, normalization.method = "LogNormalize", scale.factor = 10000)
lymphaticendothelial <- FindVariableFeatures(lymphaticendothelial, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(lymphaticendothelial)
lymphaticendothelial <- ScaleData(lymphaticendothelial, features = all.genes)
lymphaticendothelial <- RunPCA(object = lymphaticendothelial, verbose = FALSE)
ElbowPlot(lymphaticendothelial, ndims = 30)
lymphaticendothelial <- FindNeighbors(object = lymphaticendothelial, dims = 1:20)

#peribronchial
peribronchial <- NormalizeData(peribronchial, normalization.method = "LogNormalize", scale.factor = 10000)
peribronchial <- FindVariableFeatures(peribronchial, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(peribronchial)
peribronchial <- ScaleData(peribronchial, features = all.genes)
peribronchial <- RunPCA(object = peribronchial, verbose = FALSE)
ElbowPlot(peribronchial, ndims = 30)
peribronchial <- FindNeighbors(object = peribronchial, dims = 1:20)

#seven
seven <- NormalizeData(seven, normalization.method = "LogNormalize", scale.factor = 10000)
seven <- FindVariableFeatures(seven, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(seven)
seven <- ScaleData(seven, features = all.genes)
seven <- RunPCA(object = seven, verbose = FALSE)
ElbowPlot(seven, ndims = 30)
seven <- FindNeighbors(object = seven, dims = 1:20)

#fourteen
fourteen <- NormalizeData(fourteen, normalization.method = "LogNormalize", scale.factor = 10000)
fourteen <- FindVariableFeatures(fourteen, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(fourteen)
fourteen <- ScaleData(fourteen, features = all.genes)
fourteen <- RunPCA(object = fourteen, verbose = FALSE)
ElbowPlot(fourteen, ndims = 30)
fourteen <- FindNeighbors(object = fourteen, dims = 1:20)

#twentyfive
twentyfive <- NormalizeData(twentyfive, normalization.method = "LogNormalize", scale.factor = 10000)
twentyfive <- FindVariableFeatures(twentyfive, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(twentyfive)
twentyfive <- ScaleData(twentyfive, features = all.genes)
twentyfive <- RunPCA(object = twentyfive, verbose = FALSE)
ElbowPlot(twentyfive, ndims = 30)
twentyfive <- FindNeighbors(object = twentyfive, dims = 1:20)
```


```{r idents+markers, message=FALSE, warning=FALSE}
# endothelial
Idents(endothelial) <- endothelial$condition
endothelial.markers <- FindMarkers(endothelial,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(endothelial.markers, file = "output/endothelial.markers.rds")
# smoothmuscle
Idents(smoothmuscle) <- smoothmuscle$condition
smoothmuscle.markers <- FindMarkers(smoothmuscle,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(smoothmuscle.markers, file = "output/smoothmuscle.markers.rds")
# pericyte
Idents(pericyte) <- pericyte$condition
pericyte.markers <- FindMarkers(pericyte,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(pericyte.markers, file = "output/pericyte.markers.rds")
# type2pneumocyte
Idents(type2pneumocyte) <- type2pneumocyte$condition
type2pneumocyte.markers <- FindMarkers(type2pneumocyte,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(type2pneumocyte.markers, file = "output/type2pneumocyte.markers.rds")
# type1pneumocyte
Idents(type1pneumocyte) <- type1pneumocyte$condition
type1pneumocyte.markers <- FindMarkers(type1pneumocyte,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(type1pneumocyte.markers, file = "output/type1pneumocyte.markers.rds")
# ciliated
Idents(ciliated) <- ciliated$condition
ciliated.markers <- FindMarkers(ciliated,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(ciliated.markers, file = "output/ciliated.markers.rds")
# mesothelial
Idents(mesothelial) <- mesothelial$condition
mesothelial.markers <- FindMarkers(mesothelial,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(mesothelial.markers, file = "output/mesothelial.markers.rds")
# adventitialfibroblast
Idents(adventitialfibroblast) <- adventitialfibroblast$condition
adventitialfibroblast.markers <- FindMarkers(adventitialfibroblast,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(adventitialfibroblast.markers, file = "output/adventitialfibroblast.markers.rds")
# alveolarfibroblast
Idents(alveolarfibroblast) <- alveolarfibroblast$condition
alveolarfibroblast.markers <- FindMarkers(alveolarfibroblast,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(alveolarfibroblast.markers, file = "output/alveolarfibroblast.markers.rds")
# gcb
Idents(gcb) <- gcb$condition
gcb.markers <- FindMarkers(gcb,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(gcb.markers, file = "output/gcb.markers.rds")
# immune
Idents(immune) <- immune$condition
immune.markers <- FindMarkers(immune,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(immune.markers, file = "output/immune.markers.rds")

# capillaryendothelial
Idents(capillaryendothelial) <- capillaryendothelial$condition
capillaryendothelial.markers <- FindMarkers(capillaryendothelial,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(capillaryendothelial.markers, file = "output/capillaryendothelial.markers.rds")
# peribronchial
Idents(peribronchial) <- peribronchial$condition
peribronchial.markers <- FindMarkers(peribronchial,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(peribronchial.markers, file = "output/peribronchial.markers.rds")
# lymphaticendothelial
Idents(lymphaticendothelial) <- lymphaticendothelial$condition
lymphaticendothelial.markers <- FindMarkers(lymphaticendothelial,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(lymphaticendothelial.markers, file = "output/lymphaticendothelial.markers.rds")

# Seven
Idents(seven) <- seven$condition
seven.markers <- FindMarkers(seven,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
saveRDS(seven.markers, file = "output/seven.markers.rds")

# fourteen
Idents(fourteen) <- fourteen$condition
fourteen.markers <- FindMarkers(fourteen,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)

# twentyfive
Idents(twentyfive) <- twentyfive$condition
twentyfive.markers <- FindMarkers(twentyfive,ident.2 = "Control",ident.1 = "GAA KO",min.pct = 0.0,logfc.threshold = 0.01)
```

```{r resave-all-subsets, message=FALSE, warning=FALSE}
saveRDS(endothelial, file = "output/endothelial.rds")
saveRDS(smoothmuscle, file = "output/smoothmuscle.rds")
saveRDS(pericyte, file = "output/pericyte.rds")
saveRDS(type2pneumocyte, file = "output/type2pneumocyte.rds")
saveRDS(type1pneumocyte, file = "output/type1pneumocyte.rds")
saveRDS(ciliated, file = "output/ciliated.rds")
saveRDS(mesothelial, file = "output/mesothelial.rds")
saveRDS(adventitialfibroblast, file = "output/adventitialfibroblast.rds")
saveRDS(alveolarfibroblast, file = "output/alveolarfibroblast.rds")
saveRDS(goblet, file = "output/goblet.rds")
saveRDS(club, file = "output/club.rds")
saveRDS(basal, file = "output/basal.rds")
saveRDS(immune, file = "output/immune.rds")

saveRDS(capillaryendothelial, file = "output/capillaryendothelial.rds")
saveRDS(lymphaticendothelial, file = "output/lymphaticendothelial.rds")
saveRDS(peribronchial, file = "output/peribronchial.rds")
saveRDS(seven, file = "output/seven.rds")
saveRDS(fourteen, file = "output/fourteen.rds")
saveRDS(twentyfive, file = "output/twentyfive.rds")
```

```{r volcanoplots, message=FALSE, warning=FALSE}
DimPlot(merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
EnhancedVolcano(endothelial.markers,
                title = "Control vs GAA KD, Endothelial",
                #  selectLab = m$V1,
                lab = rownames(endothelial.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(smoothmuscle.markers,
                title = "Control vs GAA KD, Smooth Muscle",
                #  selectLab = m$V1,
                lab = rownames(smoothmuscle.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(pericyte.markers,
                title = "Control vs GAA KD, Pericyte",
                #  selectLab = m$V1,
                lab = rownames(pericyte.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(type2pneumocyte.markers,
                title = "Control vs GAA KD, Type 2 Pneumocyte",
                #  selectLab = m$V1,
                lab = rownames(type2pneumocyte.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(type1pneumocyte.markers,
                title = "Control vs GAA KD, Type 1 Pneumocyte",
                #  selectLab = m$V1,
                lab = rownames(type1pneumocyte.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(ciliated.markers,
                title = "Control vs GAA KD, Ciliated",
                #  selectLab = m$V1,
                lab = rownames(ciliated.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(mesothelial.markers,
                title = "Control vs GAA KD, Mesothelial",
                #  selectLab = m$V1,
                lab = rownames(mesothelial.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(adventitialfibroblast.markers,
                title = "Control vs GAA KD, Adventitial Fibroblast",
                #  selectLab = m$V1,
                lab = rownames(adventitialfibroblast.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(alveolarfibroblast.markers,
                title = "Control vs GAA KD, Alveolar Fibroblast",
                #  selectLab = m$V1,
                lab = rownames(alveolarfibroblast.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(gcb.markers,
                title = "Control vs GAA KD, Goblet+Club+Basal",
                #  selectLab = m$V1,
                lab = rownames(gcb.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(immune.markers,
                title = "Control vs GAA KD, Immune",
                #  selectLab = m$V1,
                lab = rownames(immune.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(capillaryendothelial.markers,
                title = "Control vs GAA KD, Capillary Endothelial",
                #  selectLab = m$V1,
                lab = rownames(capillaryendothelial.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(lymphaticendothelial.markers,
                title = "Control vs GAA KD, Lymphatic Endothelial",
                #  selectLab = m$V1,
                lab = rownames(lymphaticendothelial.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()

EnhancedVolcano(peribronchial.markers,
                title = "Control vs GAA KD, Peribronchial",
                #  selectLab = m$V1,
                lab = rownames(peribronchial.markers),
                x = 'avg_log2FC',
                y = 'p_val_adj',
                #ylim = c(0,10),
                #xlim = c(-1,1),
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-2,
                FCcutoff = 0.35,
                pointSize = 3.0,
                labSize = 4.5,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = F,
                colAlpha = 4/5,
                legendLabels=c('NS','log2 fold-change','P value',
                         'P value & log2 fold-change'),
                legendPosition = 'left',
                legendLabSize = 10,
                legendIconSize = 4.0,
                drawConnectors = F,widthConnectors = 0.75, arrowheads = TRUE
)+NoLegend()
```

```{r furthercleaning, message=FALSE, warning=FALSE}
merge <- FindClusters(merge, resolution = 10)
DimPlot(merge, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
merge_rm_clusters <- c(83, 100, 91, 75, 85, 106, 70, 69, 98, 95)
merge1 <- subset(x = merge, idents = merge_rm_clusters, invert = TRUE)
DimPlot(merge1, reduction = "umap", label = TRUE, pt.size = 0.001) + NoLegend()
```

```{r renormalize, message=FALSE, warning=FALSE}
merge1 <- NormalizeData(merge1, normalization.method = "LogNormalize", scale.factor = 10000)
merge1 <- FindVariableFeatures(merge1, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(merge1)
merge1 <- ScaleData(merge1, features = all.genes)
merge1 <- RunPCA(object = merge1, verbose = FALSE)
ElbowPlot(merge1, ndims = 30)
merge1 <- FindNeighbors(object = merge1, dims = 1:20)
merge1 <- FindClusters(object = merge1, resolution = 1)
merge1 <- RunUMAP(object = merge1, dims = 1:20,min.dist = 1, n.neighbors = 40, spread = 5, local.connectivity = 20)

DimPlot(merge1, reduction = "umap", label = TRUE)
DimPlot(merge1, reduction = "umap", label = F,group.by = "condition")
saveRDS(merge1, file = "output/merge1.rds")

merge1.markers <- FindAllMarkers(merge1, only.pos = TRUE, min.pct = 0.25,
                                  logfc.threshold = 0.25)
saveRDS(merge1.markers, file = "output/merge1.markers.rds")
DimPlot(merge1, reduction = "umap", label = TRUE, pt.size = 0.001)
```

```{r dotplot, message=FALSE, warning=FALSE}
markergenes <- c("Ces1d", "Npnt", "Wnt2", "Pdgfra", "Pi16", "Ccl11", "Il33", "Adh7", "Pdgfrb", "Cspg4", "Mcam", "Hhip", "Fgf18", "Dcn", "Msln", "Wt1", "Tmem100", "Ednrb", "Pecam1", "Acta2", "Myh11", "Sftpc", "Sftpd", "Mmrn1", "Lyve1", "Foxj1", "Scgb1a1", "Bpifb1", "Rtkn2", "Cd79b", "Ptprc", "Trbc2", "Cd8b1", "Ly6c2")

DotPlot(
  object = merge,
  assay = NULL,
  features = markergenes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  idents = NULL,
  group.by = NULL,
  split.by = NULL,
  cluster.idents = FALSE,
  scale = TRUE,
  scale.by = "radius",
  scale.min = NA,
  scale.max = NA
)
```


```{r cellphonedb, message=FALSE, warning=FALSE}
# Basic function to convert mouse to human gene names
alldata <- merge
rm(merge, merge.markers)
# matrix1 <- as.data.frame(alldata@assays$RNA@data)
# matrix1 <- matrix1[rowSums(matrix1[,2:dim(matrix1)[2]])!=0,]
# saveRDS(matrix1, file = "output/matrix1.rds")

### If you are using a mouse data, then its needed to convert the gene names to human orthologs
human = useEnsembl("ensembl", dataset = "hsapiens_gene_ensembl")
mouse = useEnsembl("ensembl", dataset = "mmusculus_gene_ensembl")
genesV2 = getLDS(attributes = c("mgi_symbol"), filters = "mgi_symbol", values = rownames(alldata@assays$RNA@data) , mart = mouse, attributesL = c("hgnc_symbol","hgnc_id",'ensembl_gene_id'), martL = human, uniqueRows=T)
print(head(genesV2))
matrix1 <- matrix1[match(genesV2$MGI.symbol,rownames(alldata)),]
matrix1$gene <- genesV2$Gene.stable.ID
matrix1 <- matrix1 %>%
  dplyr::select(gene, everything())
rownames(matrix1) <- NULL

### Subseting the matrix
s1 <- grepl('Control',alldata@meta.data$condition)
s2 <- grepl('GAA KO',alldata@meta.data$condition)
s1[match('gene',colnames(matrix1))] <- TRUE
s2[match('gene',colnames(matrix1))] <- TRUE
saveRDS(s1, file = "output/s1.rds")
saveRDS(s2, file = "output/s2.rds")

## Checking the dimensions and writing counts table
print(dim(matrix1[,s1]))
print(dim(matrix1[,s2]))
write.table(matrix1[,s1], "cellphonedbfiles/s1_filtered_hcount.csv",row.names=F,sep=',')
write.table(matrix1[,s2], "cellphonedbfiles/s2_filtered_hcount.csv",row.names=F,sep=',')

# generate metadata
metadata <- data.frame(cells=rownames(alldata@meta.data[grepl('Control',alldata@meta.data$condition),]),
                       cluster=alldata@meta.data$clusters[grepl('Control',alldata@meta.data$condition)])
metadata_s2 <- data.frame(cells=rownames(alldata@meta.data[!grepl('Control',alldata@meta.data$condition),]),
                          cluster=alldata@meta.data$clusters[!grepl('Control',alldata@meta.data$condition)]) ## Just negate grepl('Control',alldata@meta.data$condition),]
print('Writing Metadata')
write.csv(metadata, 'cellphonedbfiles/s1_filtered_meta.csv', row.names=FALSE)
write.csv(metadata_s2, 'cellphonedbfiles/s2_filtered_meta.csv', row.names=FALSE)
```

```{r cellphonedb1, message=FALSE, warning=FALSE}
cellphone_for_seurat <- function(obj, orgdb, prefix, slot = "data",
    assay = NULL){
    flog.info("Using counts from slot %s and assay %s.", slot,
        ifelse(is.null(assay), DefaultAssay(obj),  assay))
    counts <- as.data.frame(
        GetAssayData(obj, slot = slot, assay = assay)
    )
    counts <- .fixSymbols(counts)
    ids <- mapIds(orgdb, rownames(counts), 'ENSEMBL', 'SYMBOL')
    counts$ensembl_gene_id <- ids
    counts <- counts[!is.na(counts$ensembl_gene_id),]
    counts <- cbind(counts[,which(colnames(counts) == 'ensembl_gene_id')], counts)

    colnames(counts)[1] <- 'Gene'
    counts$ensembl_gene_id <- NULL
    colnames(counts) <- make.names(colnames(counts))

    metadata <- data.frame(Cell = make.names(Cells(obj)),
                           cell_type = Idents(obj))


    filename <- .get_sub_path(prefix, "cellphonedb", "_counts.txt")
    flog.info("Writing count matrix to %s...", filename)
    write.table(counts,
            file = filename,
            quote = FALSE,
            col.names = TRUE,
            row.names = FALSE,
            sep = '\t')
    filename <- .get_sub_path(prefix, "cellphonedb", "_metadata.txt")
    write.table(metadata,
            file = filename,
            quote = FALSE,
            col.names = TRUE,
            row.names = FALSE,
            sep = '\t')
}
cellphone_for_seurat(alld)
```

```{r cellphonedb-GAAKO, message=FALSE, warning=FALSE}
# subset based on control vs KO
GAAKO <- subset(x = alldata, subset = condition == "GAA KO")
saveRDS(GAAKO, file = "output/GAAKO.rds")
Control <- subset(x = alldata, subset = condition == "Control")
saveRDS(Control, file = "output/Control.rds")


# metadata
meta_data <- data.frame(cells=rownames(GAAKO@meta.data), cluster=GAAKO@meta.data$clusters)
write.table(meta_data, "cellphonedbfiles/GAAKO_cellphonedb_meta.txt", sep="\t", quote=F, row.names=F)

# counts
matrix1 <- as.data.frame(GAAKO@assays$RNA@data)
matrix1 <- matrix1[rowSums(GAAKO[,2:dim(matrix1)[2]])!=0,]
human = useEnsembl("ensembl", dataset = "hsapiens_gene_ensembl")
mouse = useEnsembl("ensembl", dataset = "mmusculus_gene_ensembl")
genesV2 = getLDS(attributes = c("mgi_symbol"),
                 filters = "mgi_symbol",
                 values = rownames(GAAKO@assays$RNA@data) ,
                 mart = mouse,
                 attributesL = c("hgnc_symbol","hgnc_id",'ensembl_gene_id'),
                 martL = human, uniqueRows=T)
matrix1 <- matrix1[match(genesV2$MGI.symbol,rownames(GAAKO)),]
matrix1$gene <- genesV2$Gene.stable.ID
matrix1 <- matrix1 %>%
  dplyr::select(gene, everything())
rownames(matrix1) <- NULL
write.table(matrix1, "cellphonedbfiles/GAAKO_filtered_hcount.csv",row.names=F,sep=',')
```

```{r cellphonedb-Control, message=FALSE, warning=FALSE}
# subset based on control vs KO
GAAKO <- subset(x = alldata, subset = condition == "GAA KO")
saveRDS(GAAKO, file = "output/GAAKO.rds")
Control <- subset(x = alldata, subset = condition == "Control")
saveRDS(Control, file = "output/Control.rds")


# metadata
meta_data <- data.frame(cells=rownames(Control@meta.data), cluster=Control@meta.data$clusters)
write.table(meta_data, "cellphonedbfiles/Control_cellphonedb_meta.txt", sep="\t", quote=F, row.names=F)

# counts
matrix1 <- as.data.frame(Control@assays$RNA@data)
matrix1 <- matrix1[rowSums(Control[,2:dim(matrix1)[2]])!=0,]
human = useEnsembl("ensembl", dataset = "hsapiens_gene_ensembl")
mouse = useEnsembl("ensembl", dataset = "mmusculus_gene_ensembl")
genesV2 = getLDS(attributes = c("mgi_symbol"),
                 filters = "mgi_symbol",
                 values = rownames(Control@assays$RNA@data) ,
                 mart = mouse,
                 attributesL = c("hgnc_symbol","hgnc_id",'ensembl_gene_id'),
                 martL = human, uniqueRows=T)
matrix1 <- matrix1[match(genesV2$MGI.symbol,rownames(Control)),]
matrix1$gene <- genesV2$Gene.stable.ID
matrix1 <- matrix1 %>%
  dplyr::select(gene, everything())
rownames(matrix1) <- NULL
write.table(matrix1, "cellphonedbfiles/Control_filtered_hcount.csv",row.names=F,sep=',')
```










